name: deconstructor tests

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    pre_job:
        # continue-on-error: true # Uncomment once integration is finished
        runs-on: ubuntu-latest
    
        # Map a step output to a job output
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@master
              # with:
                # All of these options are optional, so you can remove them if you are happy with the defaults
                # concurrent_skipping: 'never'
                # skip_after_successful_duplicate: 'true'
                # paths_ignore: '["**/README.md", "**/docs/**"]'
                # do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

    main:
        needs: pre_job
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.0', '8.1']
                stability: [prefer-stable]
        name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
        continue-on-error: ${{ matrix.php == '8.1' }}

        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: forge
                ports:
                    - 33306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@verbose
              with:
                php-version: ${{ matrix.php }}
                ini-values: error_reporting=E_ALL
                tools: composer:v2
                coverage: none

            - name: Install dependencies
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 5
                max_attempts: 5
                command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

            - name: Execute tests
              run: vendor/bin/phpunit --verbose
              env:
                DB_PORT: ${{ job.services.mysql.ports[3306] }}
                DB_USERNAME: root

            - name: Run composer update
              run: composer update -n --prefer-dist --optimize-autoloader
              env:
                APP_ENV: testing

            - name: Store artifacts
              uses: actions/upload-artifact@v2
              with:
                name: logs
                path: |
                    vendor/orchestra/testbench-core/laravel/storage/logs
                    !vendor/**/.gitignore


