name: firebender/deconstructor Tests

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    linux_tests:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: forge
                ports:
                    - 33306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        strategy:
            fail-fast: true
            matrix:
                php: ['8.0', '8.1']
                stability: [prefer-stable]

        name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@verbose
              with:
                php-version: ${{ matrix.php }}
                ini-values: error_reporting=E_ALL
                tools: composer:v2
                coverage: none

            - name: Install dependencies
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 5
                max_attempts: 5
                command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

            - name: Execute tests
              run: vendor/bin/phpunit --verbose
              env:
                DB_PORT: ${{ job.services.mysql.ports[3306] }}
                DB_USERNAME: root

            - name: Run composer update
              run: composer update -n --prefer-dist --optimize-autoloader
              env:
                APP_ENV: testing

            - name: Store artifacts
              uses: actions/upload-artifact@v2
              with:
                name: logs
                path: |
                    vendor/orchestra/testbench-core/laravel/storage/logs
                    !vendor/**/.gitignore


